{
  "hash": "0d55c88eae78a5a81d3a40c8cdf2d2fa",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Triple Double Russ, Revisited\"\ndate: \"2026-08-12\"\nauthor: \"Kivan Polimis\"\ndescription: \"Four seasons after the original post, I re-scrape Russell Westbrook's full game log and re-test the thesis: do his teams really win more when he records a triple double? With 345 more team games and a late-career move to the bench, the answer holds, but it now says less about present-day Westbrook than it did in 2022.\"\ncategories: [sports-analytics, python]\ndraft: false\njupyter: blog\nexecute:\n  cache: false\n---\n\nIn March 2022 I wrote [Triple Double Russ](../triple-double-russ/), which scraped\nRussell Westbrook's game log and asked a simple question: when he records a triple\ndouble, do his teams win more often? The answer then was yes, and by a wide,\nstatistically significant margin. That post was a snapshot of a career still in\nmotion. Westbrook has since played four more seasons and changed teams three times,\nmoving from a featured star to a reserve. This revisit re-collects the data through\nthe 2025-26 season and asks two things: is the same analysis still reproducible, and\ndoes the original thesis still hold?\n\nI am keeping the [original post](../triple-double-russ/) unchanged as a 2022 time\ncapsule. Everything below is recomputed from a fresh scrape.\n\n## Is data collection still possible?\n\nYes, with one repair. Basketball-Reference still publishes Westbrook's per-season game\nlogs at the same URLs the original post used, for instance\n[the 2025-26 log](https://www.basketball-reference.com/players/w/westbru01/gamelog/2026),\nand a plain request still returns them. What changed is the markup. The 2022 scraper\nkeyed on the old game-log table and its column layout; the site has since renamed the\ntable to `player_game_log_reg` and moved every statistic behind a `data-stat`\nattribute (`pts`, `trb`, `ast`, `game_result`). A scraper written against the 2022\npage returns an empty table today rather than an error, which is the quiet kind of\nfailure worth guarding against. The rewritten scraper lives in\n[`fetch_westbrook_data.py`](fetch_westbrook_data.py) and raises loudly if the expected\ntable is missing.\n\nTwo practical notes carried over from the original. Basketball-Reference rate-limits\nscrapers, so the fetch script sleeps between requests. And to keep this page building\nwithout touching the network, the scrape is cached to a CSV that the analysis below\nreads. The numbers here are current as of the 2025-26 season; re-running the fetch\nscript later will collect more games.\n\n\n## What the updated data looks like\n\nThe fresh scrape covers every regular-season team game from Westbrook's 2008-09 rookie\nyear through 2025-26. The original post had 1,093 team games to work with; this one has\n1\\,438.\n\n::: {#totals .cell execution_count=2}\n``` {.python .cell-code}\nprint(f\"Career team games: {career_games}\")\nprint(f\"Active for {active_games} of them ({active_pct:.2f}%)\")\nprint(f\"Triple doubles: {td_games} ({td_rate:.2f}% of active games)\")\nprint(f\"Active games without a triple double: {non_td_games}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCareer team games: 1438\nActive for 1301 of them (90.47%)\nTriple doubles: 209 (16.06% of active games)\nActive games without a triple double: 1092\n```\n:::\n:::\n\n\nThe triple-double count is the load-bearing number, so it is worth checking against an\nauthority. Basketball-Reference's\n[career triple-double leaderboard](https://www.basketball-reference.com/leaders/trp_dbl_career.html)\nlists Westbrook first all-time with 209 as of the 2025-26 season. The scrape-and-count\nhere returns 209, an exact match. The definition is unchanged from\n2022: a triple double is any game where three of points, rebounds, assists, steals, or\nblocks reach double digits, which in practice is almost always points, rebounds, and\nassists.\n\n## Does the thesis still hold?\n\nThe 2022 post found that Westbrook's teams won 73.58% of games in which he recorded a\ntriple double, against 55.79% when he did not. The updated numbers:\n\n::: {#cell-win-pct-table .cell execution_count=3}\n``` {.python .cell-code}\npd.DataFrame(\n    {\"Win %\": [f\"{career_win:.2f}%\", f\"{active_win:.2f}%\",\n               f\"{td_win:.2f}%\", f\"{non_td_win:.2f}%\"]},\n    index=[\"Career\", \"Active\", \"With a triple double\", \"Without a triple double\"],\n)\n```\n\n::: {#win-pct-table .cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Win %</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Career</th>\n      <td>56.33%</td>\n    </tr>\n    <tr>\n      <th>Active</th>\n      <td>56.73%</td>\n    </tr>\n    <tr>\n      <th>With a triple double</th>\n      <td>73.21%</td>\n    </tr>\n    <tr>\n      <th>Without a triple double</th>\n      <td>53.57%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe thesis holds. Westbrook's teams still win about\n73% of the games in which he records a triple double, a figure\nthat has barely moved in four seasons, and only 54% of the\ngames in which he does not. If anything the gap has widened slightly, from roughly 18\npoints in 2022 to 19\\.6 points now, because his non-triple-double\nwin rate has drifted down as his teams have gotten worse. A two-proportion z-test\nrejects the null that the two win rates are equal.\n\n::: {#ztest .cell execution_count=4}\n``` {.python .cell-code}\nprint(f\"z = {z_stat:.3f}, p = {p_value:.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nz = 5.249, p = 1.53e-07\n```\n:::\n:::\n\n\nThat the relationship survived four more seasons and three team changes is the strong\nform of the result. It is also where caution belongs. A triple double is not a treatment\napplied at random. It marks a game in which Westbrook played heavy minutes and stayed\ninvolved on both ends, and those games cluster in the seasons where he was a featured\nstarter on a competitive team, for instance his 2016-17 MVP campaign in Oklahoma City\nand his 2020-21 season in Washington. The win-percentage gap is real, but it is a\nstatement about the kind of game a triple double signals, not evidence that chasing the\ntenth assist causes the win.\n\nThe late-career data makes that caveat concrete rather than theoretical.\n\n## The role change the original post could not see\n\nSince 2023, Westbrook has been a reserve, moving from the Clippers to the Nuggets to the\nKings and coming off the bench for most of those games. His triple-double rate collapsed\naccordingly. The seasonal counts tell the story better than any summary statistic.\n\n::: {#cell-fig-seasonal .cell execution_count=5}\n``` {.python .cell-code}\nsns.set_style(\"white\")\nfig, ax = plt.subplots(figsize=(12, 6))\nlabels = [f\"'{str(y)[2:]}\" for y in td_by_season.index]\nbars = ax.bar(labels, td_by_season.values, color=\"#1f4e99\")\nax.set(xlabel=\"Season (ending year)\",\n       ylabel=\"Games with a triple double\",\n       title=\"Russell Westbrook triple doubles by season\")\nfor bar, val in zip(bars, td_by_season.values):\n    if val:\n        ax.text(bar.get_x() + bar.get_width() / 2, val + 0.4, str(val),\n                ha=\"center\", va=\"bottom\", fontsize=9)\nsns.despine()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Triple doubles by season, from Westbrook's 2008-09 rookie year through 2025-26. The peak seasons are his post-Durant years in Oklahoma City, Houston, and Washington; the collapse after 2022 tracks his move to a bench role.](index_files/figure-html/fig-seasonal-output-1.png){#fig-seasonal width=954 height=521}\n:::\n:::\n\n\nThe four seasons added since the original post contributed\n15 triple doubles combined, fewer\nthan he recorded in the single 2016-17 season. The thesis, then, is now carried almost\nentirely by his prime. It describes 2017-era Westbrook accurately and 2026-era\nWestbrook barely, because the reserve version of him rarely plays the kind of game that\nproduces a triple double in the first place. This is the generalizability caution in\npractice. A relationship estimated over a career can hold in aggregate while saying\nlittle about the player as he exists today.\n\n## Home, away, and the Durant question\n\nThe original post split triple doubles by location and marked Durant's 2016 departure\nfrom Oklahoma City, on the theory that Westbrook's triple-double era began once he was\nthe unambiguous focal point of the offense.\n\n::: {#cell-fig-location .cell execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(13, 6))\nyears = list(td_by_loc.index)\nax.plot(years, td_by_loc.get(\"Home\", 0), marker=\"o\", label=\"Home\")\nax.plot(years, td_by_loc.get(\"Away\", 0), marker=\"o\", label=\"Away\")\nax.axvline(x=2016.5, color=\"k\", linestyle=\"--\")\nax.set(xlabel=\"Season (ending year)\",\n       ylabel=\"Games with a triple double\",\n       title=\"Russell Westbrook triple doubles by location\")\nax.legend([\"Home\", \"Away\", \"Durant leaves OKC\"], loc=\"upper right\")\nsns.despine()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Triple doubles by season, split by home and away. The dashed line marks Kevin Durant's 2016 departure from Oklahoma City, after which Westbrook's triple-double production jumped.](index_files/figure-html/fig-location-output-1.png){#fig-location width=1028 height=521}\n:::\n:::\n\n\nThe split by era is stark:\n\n::: {#kd-split .cell execution_count=7}\n``` {.python .cell-code}\nprint(f\"With Durant (through 2015-16):   {td_with_kd} triple doubles\")\nprint(f\"After Durant (2016-17 onward):   {td_without_kd} triple doubles\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWith Durant (through 2015-16):   37 triple doubles\nAfter Durant (2016-17 onward):   172 triple doubles\n```\n:::\n:::\n\n\nWestbrook recorded 37 triple doubles across his eight seasons\nsharing a team with Durant and 172 in the seasons after. Some\nof that is simply age and tenure, an older Westbrook with the ball in his hands more\noften, so I would not read the Durant departure as the sole cause. But the timing is\nhard to ignore, and it lines up with the win-percentage story: the triple-double\nseasons are the seasons in which Westbrook was the engine of his team.\n\n## Margins: still no sign of selfish stat-chasing\n\nThe sharpest criticism of Westbrook is that he chases triple doubles at his team's\nexpense. If that were true, we would expect his teams to lose by more in games where he\ngets a triple double, the empty-stat-line loss. The margins say the opposite.\n\n::: {#cell-margins .cell execution_count=8}\n``` {.python .cell-code}\npd.DataFrame(\n    {\"Avg. margin\": [f\"{td_win_margin:+.2f}\", f\"{non_td_win_margin:+.2f}\",\n                     f\"{td_loss_margin:+.2f}\", f\"{non_td_loss_margin:+.2f}\"]},\n    index=[\"Triple-double wins\", \"Non-triple-double wins\",\n           \"Triple-double losses\", \"Non-triple-double losses\"],\n)\n```\n\n::: {#margins .cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Avg. margin</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Triple-double wins</th>\n      <td>+11.61</td>\n    </tr>\n    <tr>\n      <th>Non-triple-double wins</th>\n      <td>+11.54</td>\n    </tr>\n    <tr>\n      <th>Triple-double losses</th>\n      <td>-7.45</td>\n    </tr>\n    <tr>\n      <th>Non-triple-double losses</th>\n      <td>-10.74</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWhen Westbrook's teams win, the margin is nearly identical whether or not he records a\ntriple double (11\\.6 against\n11\\.5). When they lose, they lose by\n*less* with a triple double (\\-7\\.4) than without\n(\\-10\\.7). That is the same conclusion the 2022 post\nreached, and four more seasons did not disturb it. Whatever a Westbrook triple double\nis, it is not a marker of a team quietly losing while he pads his line.\n\n## Review\n\nThe 2022 result survives replication. Westbrook's teams win far more with a triple\ndouble (73%) than without (54%), the\ndifference is statistically significant, and the margin data shows no evidence that his\ntriple doubles come at his team's expense. The scrape is still possible, once the table\nname is repaired, and the count still matches Basketball-Reference to the game.\n\nWhat the extra four seasons add is a caveat the original post had no way to see. The\nrelationship is anchored in Westbrook's prime, and his move to the bench has made triple\ndoubles rare enough that the thesis now describes a version of him that no longer takes\nthe floor most nights. The statistic is durable. The player it was measuring has moved\non. Both things can be true, and holding them together is the honest reading of the\nupdated data.\n\n## Footnotes\n\n::: {#versions .cell execution_count=9}\n``` {.python .cell-code}\nimport sys\nimport IPython\nimport matplotlib as mpl\n\nprint(\"originally published 2022-03-06; revisited 2026-08-12\")\nprint(f\"Python:     {sys.version.split()[0]}\")\nprint(f\"pandas:     {pd.__version__}\")\nprint(f\"numpy:      {np.__version__}\")\nprint(f\"seaborn:    {sns.__version__}\")\nprint(f\"matplotlib: {mpl.__version__}\")\nprint(f\"IPython:    {IPython.__version__}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\noriginally published 2022-03-06; revisited 2026-08-12\nPython:     3.11.14\npandas:     2.3.3\nnumpy:      2.3.5\nseaborn:    0.13.2\nmatplotlib: 3.10.8\nIPython:    9.8.0\n```\n:::\n:::\n\n\nThe scraping code is in [`fetch_westbrook_data.py`](fetch_westbrook_data.py), and the\ncached dataset it produces is\n[`data/westbrook_game_logs.csv`](data/westbrook_game_logs.csv). The\n[original 2022 post](../triple-double-russ/) is preserved as-is.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}